[package]
name = "hudlc"
version = "0.1.0"
edition = "2021"

[dependencies]
kdl = "6.5.0"
regex = "1.10.0" # Needed for PreParser
serde = { version = "1.0.228", features = ["derive"] }
serde_cbor = "0.11.2"

[lib]
path = "src/lib.rs"

[[bin]]
name = "hudlc"
path = "src/main.rs"
