[package]
name = "hudl-lsp"
version = "0.1.0"
edition = "2024"

[dependencies]
hudlc = { version = "0.1.0", path = ".." }
lsp-types = "0.97.0"
tokio = { version = "1.49.0", features = ["full"] }
tower-lsp = "0.20.0"
